# Generated by Django 4.1.5 on 2023-01-22 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0003_alter_profile_phongban'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='gd',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='gd', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='chucdanh',
            field=models.CharField(choices=[('Tổng giám đốc', 'Tổng giám đốc'), ('Phó tổng giám đốc', 'Phó tổng giám đốc'), ('Giám đốc dự án', 'Giám đốc dự án'), ('Trưởng phòng', 'Trưởng phòng'), ('Trưởng ban', 'Trưởng ban'), ('Chỉ huy trưởng', 'Chỉ huy trưởng'), ('Nhân viên', 'Nhân viên')], default='Nhân viên', max_length=50),
        ),
    ]
