# Generated by Django 4.1.5 on 2023-01-24 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_phanquyen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhanQuyen',
        ),
    ]
