# Generated by Django 4.1.5 on 2023-02-19 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_delete_phanquyen'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='songaynghikhongphep',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='songaynghiphep',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='sophepnam',
            field=models.FloatField(blank=True, default=12),
        ),
    ]
