# Generated by Django 4.1.7 on 2023-02-23 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_profile_songaynghiphepconlai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='songaynghiphepconlai',
            field=models.FloatField(blank=True, default=12),
        ),
    ]
