# Generated by Django 4.1.5 on 2023-01-22 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nghiphep', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
