# Generated by Django 4.1.5 on 2023-01-23 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nghiphep', '0003_alter_comment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='body',
        ),
        migrations.AddField(
            model_name='post',
            name='reason',
            field=models.TextField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='numday',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(choices=[('Nghỉ phép', 'Nghỉ phép'), ('Nghỉ không lương', 'Nghỉ không lương'), ('Nghỉ ốm', 'Nghỉ ốm'), ('Nghỉ sanh', 'Nghỉ sanh'), ('Nghỉ hôn nhân', 'Nghỉ hôn nhân'), ('Nghỉ tang lễ', 'Nghỉ tang lễ'), ('Nghỉ khác', 'Nghỉ khác')], default='Nghỉ phép', max_length=100),
        ),
    ]
