# Generated by Django 4.1.5 on 2023-01-23 08:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nghiphep', '0004_remove_post_body_post_reason_alter_post_numday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_end',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_from',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
