# Generated by Django 4.1.5 on 2023-01-23 14:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nghiphep', '0005_alter_post_date_end_alter_post_date_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_end',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_from',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
