# Generated by Django 4.1.5 on 2023-01-24 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nghiphep', '0006_alter_post_date_end_alter_post_date_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('request', 'Request'), ('waiting', 'Waiting'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('canceled', 'Canceled')], default='request', max_length=10),
        ),
    ]
