# Generated by Django 4.1.5 on 2023-01-26 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonghop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lichhop',
            name='room',
            field=models.CharField(choices=[('opal', 'OPAL'), ('ruby', 'RUBY'), ('amber', 'AMBER'), ('saphire', 'SAPHIRE'), ('diamond', 'DIAMOND')], default='ruby', max_length=15),
        ),
    ]
